# -*- coding: utf-8 -*-
"""6.2.1 numeros lideres

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bfmjTko2-HRMDIr2nX-a-VTPgSaySi8
"""

numeros = list(map(int, input().split()))
lideres = []
mayor = -1

for i in range(len(numeros) - 1, -1, -1):
    if numeros[i] > mayor:
        lideres.append(numeros[i])
        mayor = numeros[i]

lideres.reverse()
print(*lideres)