# -*- coding: utf-8 -*-
"""6.3.1 Eliminando numeros duplicados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eliu46f2R0e4k1vKIO-S7Q9WNI0EQzi
"""

numeros = list(map(int, input().split()))
vistos = set()
resultado = []

for num in numeros:
    if num not in vistos:
        resultado.append(num)
        vistos.add(num)

print(*resultado)